import { app, ipcMain, shell } from 'electron';
import { clientManager } from './client';
import { updateManager, UpdateState } from './updater';
import { windowManager } from './window';
import { settingsManager } from './settings';

/**
 * This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
 * plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
 * whether you're running in development or production).
 */
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const main = (() => {
  /**
   * Registers our Inter Process Communications.
   */
  const registerIPC = () => {
    ipcMain.on('window-rendered', onWindowRendered);
    ipcMain.on('window-close', () => {
      app.quit();
    });
    ipcMain.on('window-minimize', () => {
      windowManager.get().minimize();
    });
    ipcMain.on('link-clicked', (event, args) => {
      shell.openExternal(args);
    });
    ipcMain.on('choose-install-directory', () => {
      clientManager.chooseDirectory(() => {
        setTimeout(() => {
          updateManager.setState(UpdateState.GET_MANIFEST);
          updateManager.getManifest();
        }, 1000);
      });
    });
    ipcMain.on('refresh-update-state', () => {
      updateManager.refresh();
    });
    ipcMain.on('update-button-click', () => {
      updateManager.downloadUpdates();
    });
    ipcMain.on('on-cancel-button-clicked', () => {
      updateManager.cancel();
    });
    ipcMain.on('play-game', () => {
      clientManager.open();

      setTimeout(() => {
        app.quit();
      }, 1000);
    });
    ipcMain.on('get-settings', (event) => {
      const settings = settingsManager.storage().store;
      event.reply('settings-received', settings);
    });
    ipcMain.on('save-settings', (event, settings) => {
      settingsManager.storage().set(settings);
      app.relaunch();
      app.quit();
    });
  };

  /**
   * This method will be called when Electron has finished
   * initialization and is ready to create browser windows.
   * Some APIs can only be used after this event occurs.
   */
  const onReady = () => {
    windowManager.create(
      MAIN_WINDOW_WEBPACK_ENTRY,
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    );
  };

  /**
   * Fires when the app is quitting.
   */
  const onAppQuit = () => {
    if (updateManager.getState() === UpdateState.DOWNLOADING) {
      updateManager.cancel();
    }
  };

  /**
   * Fired when all windows are closed.
   */
  const onAllWindowClosed = () => {
    app.quit();
  };

  /**
   * When the DOM Content has been loaded we start setting
   * up our initial updater state.
   */
  const onWindowRendered = () => {
    windowManager.get().show();

    windowManager
      .get()
      .webContents.send('launcher-version-received', app.getVersion());

    /** User has either not set directory yet or has moved their client. */
    if (
      !clientManager.hasClientDirectory() ||
      !clientManager.isWarcraftDirectory(clientManager.getClientDirectory())
    ) {
      updateManager.setState(UpdateState.SETUP);
      return;
    }

    /** Otherwise - Go to patching. */
    updateManager.setState(UpdateState.GET_MANIFEST);
    updateManager.getManifest();
  };

  return {
    start: () => {
      registerIPC();
      /** Electron App Events. */
      app.on('ready', onReady);
      app.on('window-all-closed', onAllWindowClosed);
      app.on('before-quit', onAppQuit);
    },
  };
})();
